on:
  pull_request:
    branches:
    - master
jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 9.0.x
    - name: Build
      run: dotnet build Crews.PlanningCenter.Models --configuration Release